// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/skpr/pinchy/apis/pinchy/v1beta1"
	pinchyv1beta1 "github.com/skpr/pinchy/internal/clientset/typed/pinchy/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEnvironments implements EnvironmentInterface
type fakeEnvironments struct {
	*gentype.FakeClientWithList[*v1beta1.Environment, *v1beta1.EnvironmentList]
	Fake *FakePinchyV1beta1
}

func newFakeEnvironments(fake *FakePinchyV1beta1, namespace string) pinchyv1beta1.EnvironmentInterface {
	return &fakeEnvironments{
		gentype.NewFakeClientWithList[*v1beta1.Environment, *v1beta1.EnvironmentList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("environments"),
			v1beta1.SchemeGroupVersion.WithKind("Environment"),
			func() *v1beta1.Environment { return &v1beta1.Environment{} },
			func() *v1beta1.EnvironmentList { return &v1beta1.EnvironmentList{} },
			func(dst, src *v1beta1.EnvironmentList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.EnvironmentList) []*v1beta1.Environment { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.EnvironmentList, items []*v1beta1.Environment) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
