// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/skpr/pinchy/internal/clientset/typed/pinchy/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePinchyV1beta1 struct {
	*testing.Fake
}

func (c *FakePinchyV1beta1) Environments(namespace string) v1beta1.EnvironmentInterface {
	return newFakeEnvironments(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePinchyV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
