// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	pinchyv1beta1 "github.com/skpr/pinchy/apis/pinchy/v1beta1"
	scheme "github.com/skpr/pinchy/internal/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EnvironmentsGetter has a method to return a EnvironmentInterface.
// A group's client should implement this interface.
type EnvironmentsGetter interface {
	Environments(namespace string) EnvironmentInterface
}

// EnvironmentInterface has methods to work with Environment resources.
type EnvironmentInterface interface {
	Create(ctx context.Context, environment *pinchyv1beta1.Environment, opts v1.CreateOptions) (*pinchyv1beta1.Environment, error)
	Update(ctx context.Context, environment *pinchyv1beta1.Environment, opts v1.UpdateOptions) (*pinchyv1beta1.Environment, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, environment *pinchyv1beta1.Environment, opts v1.UpdateOptions) (*pinchyv1beta1.Environment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*pinchyv1beta1.Environment, error)
	List(ctx context.Context, opts v1.ListOptions) (*pinchyv1beta1.EnvironmentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *pinchyv1beta1.Environment, err error)
	EnvironmentExpansion
}

// environments implements EnvironmentInterface
type environments struct {
	*gentype.ClientWithList[*pinchyv1beta1.Environment, *pinchyv1beta1.EnvironmentList]
}

// newEnvironments returns a Environments
func newEnvironments(c *PinchyV1beta1Client, namespace string) *environments {
	return &environments{
		gentype.NewClientWithList[*pinchyv1beta1.Environment, *pinchyv1beta1.EnvironmentList](
			"environments",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *pinchyv1beta1.Environment { return &pinchyv1beta1.Environment{} },
			func() *pinchyv1beta1.EnvironmentList { return &pinchyv1beta1.EnvironmentList{} },
		),
	}
}
