// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	http "net/http"

	pinchyv1beta1 "github.com/skpr/pinchy/apis/pinchy/v1beta1"
	scheme "github.com/skpr/pinchy/internal/clientset/scheme"
	rest "k8s.io/client-go/rest"
)

type PinchyV1beta1Interface interface {
	RESTClient() rest.Interface
	EnvironmentsGetter
}

// PinchyV1beta1Client is used to interact with features provided by the pinchy.skpr.io group.
type PinchyV1beta1Client struct {
	restClient rest.Interface
}

func (c *PinchyV1beta1Client) Environments(namespace string) EnvironmentInterface {
	return newEnvironments(c, namespace)
}

// NewForConfig creates a new PinchyV1beta1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*PinchyV1beta1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new PinchyV1beta1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*PinchyV1beta1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &PinchyV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new PinchyV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *PinchyV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new PinchyV1beta1Client for the given RESTClient.
func New(c rest.Interface) *PinchyV1beta1Client {
	return &PinchyV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := pinchyv1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *PinchyV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
